version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - "jobbies_network"
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    stop_signal: SIGINT
    depends_on:
      - cache
    container_name: backend
    expose:
      - 9090
    networks:
      - "jobbies_network"
  web: 
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:9090  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - "jobbies_network"
volumes:
  cache:
    driver: local
networks:
  jobbies_network:
    external: false